<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <ImplicitUsings>disable</ImplicitUsings>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaxRev.Gdal.Core" Version="3.13.3.580" />
    <PackageReference Include="MaxRev.Gdal.LinuxRuntime.Minimal" Version="3.13.3.580" />
    <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.13.3.580" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
  </ItemGroup>

</Project>
